### PR TITLE
Fix kiss fails during update if a directory doesn't exist #3

### PR DESCRIPTION
**Pull request by kyx0r**
https://github.com/kiss-community/kiss/issues/3

### CODE REVIEW

**Comment by git-bruh** [comment]
I suggest something like this with a better error message

```
[ -d "$repo" ] || {
    log "$repo" " "
    printf "Skipping update, repository does not exist."
}
```

**Comment by kyx0r** [comment]
git-bruh <notifications@github.com> wrote:

> I suggest something like this with a better error message
>
> ```
> [ -d "$repo" ] || {
>     log "$repo" " "
>     printf "Skipping update, repository does not exist."
> }
> ```
>
> --

@git-bruh Did you delete the comment? Anyways here if why your solution is worse, first it does not handle the case of broken symlinks. Second, it is misleading the user by saying "repository does not exist." instead of more explicit, which should be "directory does not exist". Third, your solution will use more lines of code and be less efficient because there is no continue statement which may or may not have unintended side effects. 
If you don't find any false positives in my solution feel free to merge it now, I want to update my rigs.

Regards,
Kyryl.

**Comment by git-bruh** [comment]
Yeah i realised it was worse so i deleted it @kyx0r. Regarding merging, only dilyn can do that now.

**Comment by dilyn-corner** [comment]
I briefly tested it, seems fine. I'm assuming it satisfies your issue, @kyx0r.

**Pull request merged**
