### PR TITLE
kiss: implement tsort-based dependency resolution

### PR DESCRIPTION
**Pull request by illiliti**
Fixes: #29
Fixes: #30
Superseded: #32

### CODE REVIEW

**Comment by illiliti** [comment]
@E5ten @cemkeylan @aaronNGi @dilyn-corner

**Comment by aaronNGi** [comment]
Amazing work. I can't really comment on the algorithm but the syntax and style looks good. Good to merge in my opinion.

**Comment by sdsddsd1** [comment]
When a build package already exists, and it is going to rebuild, the missing (make)dependencies are not resolved.
E.g for building `xorg-server` the package `xtrans` is not installed.

**Comment by illiliti** [comment]
> Amazing work. I can't really comment on the algorithm but the syntax and style looks good. Good to merge in my opinion.

Thanks! For now, it's just a draft. There are some things need to be fixed before it can be merged.

> When a build package already exists, and it is going to rebuild, the missing (make)dependencies are not resolved.
> E.g for building `xorg-server` the package `xtrans` is not installed.

Thanks for testing! Will work on it.

**Comment by illiliti** [comment]
Closed in favor of Dylan's solution.

**Pull request closed without merging**
